name: Publish Xerris.DotNet.Data.PostgreSQL

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    uses: xerris/xerris-common-workflows/.github/workflows/build-and-publish-to-nuget.yml@main
    with:
      csproj-path: './src/Xerris.DotNet.Data.SqlServer/Xerris.DotNet.Data.SqlServer.csproj'
      nuget-package-name: 'xerris.dotnet.data.sqlserver'
      dotnet-version: '9.0.x'
      release-path: 'net9.0'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE_URI: ${{ secrets.NUGET_SOURCE_URI }}